// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.ML.Transforms.TimeSeries;

namespace CASE26_projekt
{
    public partial class DailyEnergyPredictionModel
    {
        /// <summary>
        /// model input class for DailyEnergyPredictionModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(5)]
            [ColumnName(@"Daily energy(kWh)")]
            public float Daily_energy_kWh_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DailyEnergyPredictionModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Daily energy(kWh)")]
            public float[] Daily_energy_kWh_ { get; set; }

            [ColumnName(@"Daily energy(kWh)_LB")]
            public float[] Daily_energy_kWh__LB { get; set; }

            [ColumnName(@"Daily energy(kWh)_UB")]
            public float[] Daily_energy_kWh__UB { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"C:\Users\user\Desktop\CASE_2026_projekt\Repo\CASE26_projekt\CASE26_projekt\CASE26_projekt\DailyEnergyPredictionModel.mlnet");

        public static readonly Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<TimeSeriesPredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput? input = null, int? horizon = null)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input, horizon);
        }

        private static TimeSeriesPredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var schema);
            return mlModel.CreateTimeSeriesEngine<ModelInput, ModelOutput>(mlContext);
        }
    }
}

